name: YumHub
description: A Food App project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  domain:
    path: ./domain
  core:
    path: ./core
  core_ui:
    path: ./core_ui
  navigation:
    path: ./navigation
  auth:
    path: ./features/auth
  home:
    path: ./features/home
  cart:
    path: ./features/cart
  order_history:
    path: ./features/order_history
  product_detailed_view:
    path: ./features/product_detailed_view
  settings:
    path: ./features/settings

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.13.1"
  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "core_ui/assets/logo/launch_icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - core_ui/assets/logo/
    - core_ui/assets/lottie_animations/

  fonts:
    - family: Dosis
      fonts:
        - asset: core_ui/assets/fonts/Dosis-Regular.ttf
        - asset: core_ui/assets/fonts/Dosis-Bold.ttf
