name: core
description: Project core module
version: 0.0.1

environment:
  sdk: '>=3.0.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  data:
    path: ../data
  domain:
    path: ../domain
  navigation:
    path: ../navigation

  get_it: ^7.6.0
  equatable: ^2.0.5
  flutter_bloc: ^8.1.1
  cloud_firestore: ^4.8.1
  firebase_auth: ^4.6.3
  firebase_storage: ^11.2.3
  firebase_messaging: ^14.6.3
  firebase_core: ^2.14.0
  firebase_database: ^10.2.3
  shared_preferences: ^2.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  connectivity_plus: ^4.0.1
  cached_network_image: ^3.2.3
  url_launcher: ^6.1.12
  google_sign_in: ^6.1.4
  intl: ^0.18.1
  animations: ^2.0.7
  google_nav_bar: ^5.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  hive_generator: ^2.0.0
  build_runner: ^2.4.5
  flutter_lints: ^2.0.0


flutter:
