// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjutjKRWKoiZzI8U-PSztV5W5Z7xfAoWQ',
    appId: '1:415019838765:android:14c71107a33b0d204077a4',
    messagingSenderId: '415019838765',
    projectId: 'products-cfc8b',
    databaseURL: 'https://products-cfc8b-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'products-cfc8b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXI4iaj6vehAmnb6NosseLdpLTBnkirlg',
    appId: '1:415019838765:ios:6148e1d9633b9c454077a4',
    messagingSenderId: '415019838765',
    projectId: 'products-cfc8b',
    databaseURL: 'https://products-cfc8b-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'products-cfc8b.appspot.com',
    iosClientId: '415019838765-qgjulg3l0r9me7bfte0ggjkkk0mofg0u.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodApp',
  );
}
