// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaaFQjJy2Y-YyqHNCGLkDj6qd77UszW8A',
    appId: '1:185212814532:android:052fe3de058e56d61f7591',
    messagingSenderId: '185212814532',
    projectId: 'yumhub-b2f74',
    databaseURL: 'https://yumhub-b2f74-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'yumhub-b2f74.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCW7ZMbqFP6qjvhZnpc9NV8YXQtaKr__Vs',
    appId: '1:185212814532:ios:3047c763e665b6d01f7591',
    messagingSenderId: '185212814532',
    projectId: 'yumhub-b2f74',
    databaseURL: 'https://yumhub-b2f74-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'yumhub-b2f74.appspot.com',
    androidClientId: '185212814532-hpk82aurjbm97mloc4t3hq1ok2562lev.apps.googleusercontent.com',
    iosClientId: '185212814532-til4ggh195gus1om1h4uabd273nkarl1.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodApp',
  );
}
